### ISSUE TITLE
有没有一个简单的示例呀

### ISSUE THREAD

**Issue by zhongzhihuashanghai** [shellljx/TagViewGroup#3]
楼主写的示例感觉不对呀，为什么简介里面说在xml里面定义TagViewGroup，但是在simple里面确又用的是tagimageview，这样 写让人很惆怅，还有那个addTagList()方法里面的数据如何添加也没有说明，所以能不能给个最简单最快看到效果的案例，谢谢

**Comment by shellljx** [comment]
① ... tagImageView 是示例项目对 TagViewGroup 封装的一个自定义view啊，里面封装了添加，修改TagViewGroup 的操作，方便对 TagViewGroup 的操作。
② 因为服务器返回的 Tag 组数量不定啊，所以可以在 xml 里定义一个 TagViewGroup 但是动态在代码里添加更符合现实需求。
③ 2.0 版本中 `TagviewGroup.addTagList()` 方法已经去掉了，改用 `setadapter(new TagAdapter)` 添加数据，在示例中数据是保存在 `DataRepo` 里的静态数据,现实中肯定是要从服务器下拉数据。
