### ISSUE TITLE
监听事件无效

### ISSUE THREAD

**Issue by 2327100351** [shellljx/TagViewGroup#5]
我照着demo添加的监听事件,但是没有效果,我的背景是一个视频播放器,是被拦截了,还是有什么前置条件.

**Comment by shellljx** [comment]
不需要前置条件，你可以 debug 一下看哪里出了问题，或者你把你的 demo 发给我看一下

**Comment by 2327100351** [comment]
昨天找到原因了,因为一个判断的事,我用的DIRECTION的参数是CENTER;源码中把CENTER给排除了,所以判断不出是哪个Tag的Touch事件,把CENTER的判断注释就好了,因为需求有一些不一样,所以出了一些问题,谢谢作者抽时间解答,
